version: "3.9"

services:
  api:
    build: ./backend
    container_name: face-api
    network_mode: host          # ← add
    # ports: ["8000:8000"]      # ← remove
    environment:
      # -- Supabase credentials (required) ------------------------------
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      JWT_SECRET: ${NEXTAUTH_SECRET}
    volumes:
      # Persist InsightFace model downloads
      - insight_cache:/root/.insightface
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: face-web
    network_mode: host          # ← add
    # ports: ["3000:3000"]      # ← remove
    environment:
      # -- Supabase creds (public), NextAuth secret, LAN IP -------------
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      HOST_IP: ${HOST_IP}
      NEXT_PUBLIC_HOST_URL: https://${HOST_IP}:3000
      NEXTAUTH_URL: https://${HOST_IP}:3000
    depends_on:
      - api
    restart: unless-stopped
    # Mount certificates folder if you want Next dev HTTPS files to persist
    volumes:
      - certificates_cache:/app/certificates

volumes:
  insight_cache:
  certificates_cache:
